// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIz05nxtE3IVtF6Xavab6uLMrRud5UYhA',
    appId: '1:389268929850:web:e92a35ef6aae9d9c8d6403',
    messagingSenderId: '389268929850',
    projectId: 'instagram-clone-5ad85',
    authDomain: 'instagram-clone-5ad85.firebaseapp.com',
    storageBucket: 'instagram-clone-5ad85.appspot.com',
    measurementId: 'G-FXN5P26SYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI00Yn-8nnmVpxIPoa11LhXHHwwi30gQI',
    appId: '1:389268929850:android:528b5cfd5d5ed1d58d6403',
    messagingSenderId: '389268929850',
    projectId: 'instagram-clone-5ad85',
    storageBucket: 'instagram-clone-5ad85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3orOcvOqz2DDKpZQDcvqVPzggym0rEWE',
    appId: '1:389268929850:ios:0d5200019b2bb8028d6403',
    messagingSenderId: '389268929850',
    projectId: 'instagram-clone-5ad85',
    storageBucket: 'instagram-clone-5ad85.appspot.com',
    iosClientId: '389268929850-fqe4qkoeksqg93qhsj09v2nk7s38nbro.apps.googleusercontent.com',
    iosBundleId: 'com.dangtu.instagram',
  );
}
